import type { Config } from 'tailwindcss'

export default <Partial<Config>>{
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-bright': '#2f3a4c',
        'surface': '#081425',
        'on-surface-variant': '#bcc9cd',
        'tertiary': '#c0c1ff',
        'tertiary-fixed': '#e1e0ff',
        'surface-container': '#152031',
        'tertiary-fixed-dim': '#c0c1ff',
        'on-tertiary': '#1000a9',
        'surface-container-low': '#111c2d',
        'secondary-fixed-dim': '#4edea3',
        'primary-container': '#06b6d4',
        'outline-variant': '#3d494c',
        'on-secondary-fixed-variant': '#005236',
        'on-primary': '#003640',
        'on-error': '#690005',
        'tertiary-container': '#9a9dff',
        'primary-fixed': '#acedff',
        'secondary-fixed': '#6ffbbe',
        'secondary': '#4edea3',
        'on-tertiary-fixed': '#07006c',
        'primary-fixed-dim': '#4cd7f6',
        'surface-container-lowest': '#040e1f',
        'primary': '#4cd7f6',
        'inverse-primary': '#00687a',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'inverse-on-surface': '#263143',
        'surface-variant': '#2a3548',
        'surface-container-high': '#1f2a3c',
        'on-primary-fixed': '#001f26',
        'on-secondary-fixed': '#002113',
        'error-container': '#93000a',
        'error': '#ffb4ab',
        'surface-tint': '#4cd7f6',
        'on-primary-container': '#00424f',
        'surface-container-highest': '#2a3548',
        'on-tertiary-container': '#211cb4',
        'on-surface': '#d8e3fb',
        'on-secondary-container': '#00311f',
        'on-error-container': '#ffdad6',
        'on-background': '#d8e3fb',
        'outline': '#869397',
        'background': '#081425',
        'secondary-container': '#00a572',
        'on-primary-fixed-variant': '#004e5c',
        'on-secondary': '#003824',
        'inverse-surface': '#d8e3fb',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-md': '16px',
        'stack-xs': '4px',
        'container-max': '1440px',
        'stack-sm': '8px',
        'margin-page': '32px',
        'gutter': '16px',
        'stack-lg': '24px',
      },
      fontFamily: {
        'display-sm': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'IBM Plex Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'code-md': ['JetBrains Mono', 'IBM Plex Mono', 'monospace'],
      },
      fontSize: {
        'display-sm': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'code-sm': ['12px', { lineHeight: '16px', fontWeight: '450' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'code-md': ['14px', { lineHeight: '20px', fontWeight: '450' }],
      },
    },
  },
}
