import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { randomUUID } from 'crypto';

/**
 * AI provisioner, mirroring apps/api/app/routers/ai_provisioner.py +
 * services/ai_provisioner.py. The only LLM provider in this project is Google
 * Gemini; the NestJS control plane ships no Gemini SDK, so it always runs the
 * deterministic heuristic branch (source = "heuristic"), which is exactly the
 * branch FastAPI takes when Gemini is not configured. Response shapes match the
 * FastAPI Pydantic models 1:1.
 */

type BlueprintTarget = 'local_node' | 'gcp' | 'aws' | 'azure';
type ServiceKind = 'web' | 'worker' | 'datastore' | 'cache';

interface BlueprintPort {
  container_port: number;
  host_port: number;
  protocol: string;
}
interface BlueprintVolume {
  host_path: string;
  container_path: string;
  mode: string;
}
interface InfraServiceSpec {
  name: string;
  image: string;
  kind: ServiceKind;
  ports: BlueprintPort[];
  env: Record<string, string>;
  volumes: BlueprintVolume[];
  cpu_limit: number;
  memory_mb: number;
  replicas: number;
  persistent: boolean;
  command: string | null;
}
interface InfraBlueprint {
  name: string;
  summary: string;
  services: InfraServiceSpec[];
  notes: string[];
}

// Cost rates, mirroring apps/api/app/core/config.py defaults.
const COST_RATE_CPU_CORE_HOUR = 0.031;
const COST_RATE_MEMORY_GIB_HOUR = 0.0042;
const COST_RATE_POSTGRES_HOUR = 0.08;
const COST_RATE_REDIS_HOUR = 0.04;
const COST_HOURS_PER_MONTH = 730;
const LOCAL_NODE_MAX_VCPU = 2.0;
const LOCAL_NODE_MAX_MEMORY_MB = 8192;

function q4(n: number): number {
  return Math.round(n * 10000) / 10000;
}
function q2(n: number): number {
  return Math.round(n * 100) / 100;
}

function port(container: number, host: number): BlueprintPort {
  return { container_port: container, host_port: host, protocol: 'tcp' };
}
function volume(hostPath: string, containerPath: string): BlueprintVolume {
  return { host_path: hostPath, container_path: containerPath, mode: 'rw' };
}
function service(partial: Partial<InfraServiceSpec> & { name: string; image: string }): InfraServiceSpec {
  return {
    kind: 'web',
    ports: [],
    env: {},
    volumes: [],
    cpu_limit: 0.5,
    memory_mb: 512,
    replicas: 1,
    persistent: false,
    command: null,
    ...partial,
  };
}

@Injectable()
export class AiService {
  constructor(private readonly configService: ConfigService) {}

  private geminiConfigured(): boolean {
    return Boolean((this.configService.get<string>('GEMINI_API_KEY') ?? '').trim());
  }

  getStatus(): any {
    return {
      gemini_configured: this.geminiConfigured(),
      model: this.configService.get<string>('GEMINI_MODEL', 'gemini-2.5-flash'),
      heuristic_fallback: true,
    };
  }

  private mbFromPrompt(text: string, def: number): number {
    const gb = text.match(/(\d+)\s*g(i?b)?\b/);
    if (gb) return parseInt(gb[1], 10) * 1024;
    const mb = text.match(/(\d+)\s*m(i?b)?\b/);
    if (mb) return parseInt(mb[1], 10);
    return def;
  }

  // Keyword-driven blueprint, ported from AiProvisioner._heuristic_blueprint.
  private heuristicBlueprint(prompt: string): InfraBlueprint {
    const text = prompt.toLowerCase();
    const services: InfraServiceSpec[] = [];
    const notes = [
      'Generated by the deterministic heuristic (Gemini not configured or unavailable).',
    ];

    if (text.includes('redis') || text.includes('cache')) {
      services.push(
        service({
          name: 'redis',
          image: 'redis:7-alpine',
          kind: 'cache',
          ports: [port(6379, 6379)],
          cpu_limit: 0.25,
          memory_mb: this.mbFromPrompt(text, 256),
          persistent: true,
          volumes: [volume('/var/lib/launchpad/redis', '/data')],
        }),
      );
    }
    if (text.includes('postgres') || text.includes('database') || text.includes('sql')) {
      services.push(
        service({
          name: 'postgres',
          image: 'postgres:16-alpine',
          kind: 'datastore',
          ports: [port(5432, 5432)],
          env: { POSTGRES_PASSWORD: 'change-me', POSTGRES_DB: 'app' },
          cpu_limit: 0.5,
          memory_mb: 512,
          persistent: true,
          volumes: [volume('/var/lib/launchpad/postgres', '/var/lib/postgresql/data')],
        }),
      );
    }
    if (
      text.includes('fastapi') ||
      text.includes('worker') ||
      text.includes('api') ||
      text.includes('app')
    ) {
      const isWorker = text.includes('worker') && !text.includes('api');
      services.push(
        service({
          name: isWorker ? 'worker' : 'api',
          image: 'python:3.11-slim',
          kind: isWorker ? 'worker' : 'web',
          ports: isWorker ? [] : [port(8080, 8080)],
          cpu_limit: 0.5,
          memory_mb: this.mbFromPrompt(text, 512),
          command: isWorker ? null : 'python -m http.server 8080',
        }),
      );
    }
    if (text.includes('nginx') || text.includes('web') || text.includes('frontend')) {
      services.push(
        service({
          name: 'web',
          image: 'nginx:1.27-alpine',
          kind: 'web',
          ports: [port(80, 8081)],
          cpu_limit: 0.25,
          memory_mb: 128,
        }),
      );
    }

    if (services.length === 0) {
      services.push(
        service({
          name: 'app',
          image: 'nginx:1.27-alpine',
          kind: 'web',
          ports: [port(80, 8080)],
          cpu_limit: 0.5,
          memory_mb: 256,
        }),
      );
      notes.push('No recognizable stack in the prompt; scaffolded a single web service.');
    }

    return { name: 'ai-stack', summary: prompt.trim().slice(0, 1024), services, notes };
  }

  // Guardrails, ported from AiProvisioner.validate_and_guardrail (local-node clamps).
  private validateAndGuardrail(
    blueprint: InfraBlueprint,
    target: BlueprintTarget,
  ): { blueprint: InfraBlueprint; validation: any } {
    const violations: any[] = [];
    let adjusted = false;
    const isLocal = target === 'local_node';

    if (blueprint.services.length === 0) {
      violations.push({
        code: 'no_services',
        message: 'Blueprint must contain at least one service.',
        severity: 'error',
        service: null,
      });
    }

    let totalCpu = 0;
    let totalMem = 0;
    for (const svc of blueprint.services) {
      if (isLocal) {
        if (svc.cpu_limit > LOCAL_NODE_MAX_VCPU) {
          violations.push({
            code: 'cpu_clamped',
            message: `${svc.name}: cpu_limit reduced to ${LOCAL_NODE_MAX_VCPU} vCPU (local node cap).`,
            severity: 'warning',
            service: svc.name,
          });
          svc.cpu_limit = LOCAL_NODE_MAX_VCPU;
          adjusted = true;
        }
        if (svc.memory_mb > LOCAL_NODE_MAX_MEMORY_MB) {
          violations.push({
            code: 'mem_clamped',
            message: `${svc.name}: memory reduced to ${LOCAL_NODE_MAX_MEMORY_MB} MB (local node cap).`,
            severity: 'warning',
            service: svc.name,
          });
          svc.memory_mb = LOCAL_NODE_MAX_MEMORY_MB;
          adjusted = true;
        }
      }
      totalCpu += svc.cpu_limit * svc.replicas;
      totalMem += svc.memory_mb * svc.replicas;
    }

    if (isLocal && totalCpu > LOCAL_NODE_MAX_VCPU) {
      violations.push({
        code: 'total_cpu_exceeded',
        message: `Total requested CPU ${totalCpu.toFixed(2)} vCPU exceeds the local node cap of ${LOCAL_NODE_MAX_VCPU} vCPU. Reduce replicas or split across nodes.`,
        severity: 'error',
        service: null,
      });
    }

    const hasError = violations.some((v) => v.severity === 'error');
    return {
      blueprint,
      validation: { valid: !hasError, adjusted, violations },
    };
  }

  // Cost estimate, ported from AiProvisioner.estimate_cost.
  private estimateCost(blueprint: InfraBlueprint, target: BlueprintTarget): any {
    const breakdown: any[] = [];
    let hourly = 0;
    for (const svc of blueprint.services) {
      const replicas = svc.replicas;
      const cpuCores = svc.cpu_limit * replicas;
      const memGib = (svc.memory_mb / 1024) * replicas;
      const cpuUsd = q4(cpuCores * COST_RATE_CPU_CORE_HOUR);
      const memUsd = q4(memGib * COST_RATE_MEMORY_GIB_HOUR);
      let addonUsd = 0;
      if (svc.kind === 'datastore') addonUsd = q4(COST_RATE_POSTGRES_HOUR * replicas);
      else if (svc.kind === 'cache') addonUsd = q4(COST_RATE_REDIS_HOUR * replicas);
      const lineHourly = q4(cpuUsd + memUsd + addonUsd);
      hourly += lineHourly;
      breakdown.push({
        service: svc.name,
        cpu_usd: cpuUsd,
        memory_usd: memUsd,
        addon_usd: addonUsd,
        hourly_usd: lineHourly,
      });
    }
    const hourlyUsd = q4(hourly);
    return {
      hourly_usd: hourlyUsd,
      monthly_usd: q2(hourlyUsd * COST_HOURS_PER_MONTH),
      currency: 'USD',
      self_hosted: target === 'local_node',
      breakdown,
    };
  }

  private coerceTarget(value: unknown): BlueprintTarget {
    const raw = (typeof value === 'string' ? value : '').trim().toLowerCase();
    return (['local_node', 'gcp', 'aws', 'azure'] as const).includes(raw as BlueprintTarget)
      ? (raw as BlueprintTarget)
      : 'local_node';
  }

  async generateBlueprint(payload: any): Promise<any> {
    const prompt: string = (payload?.prompt ?? '').toString();
    const target = this.coerceTarget(payload?.target);
    const nodeId: string | null = payload?.node_id ?? null;
    const heuristic = this.heuristicBlueprint(prompt);
    const { blueprint, validation } = this.validateAndGuardrail(heuristic, target);
    const cost = this.estimateCost(blueprint, target);
    return { blueprint, target, node_id: nodeId, source: 'heuristic', validation, cost };
  }

  async fixBlueprint(payload: any): Promise<any> {
    // Heuristic "fix": re-validate + re-cost the supplied blueprint (no LLM available).
    const target = this.coerceTarget(payload?.target);
    const nodeId: string | null = payload?.node_id ?? null;
    const incoming: InfraBlueprint | null = payload?.blueprint ?? null;
    const base = incoming ?? this.heuristicBlueprint((payload?.prompt ?? '').toString());
    if (!base.notes) base.notes = [];
    base.notes.push('Re-validated by the deterministic heuristic (Gemini not configured).');
    const { blueprint, validation } = this.validateAndGuardrail(base, target);
    const cost = this.estimateCost(blueprint, target);
    return { blueprint, target, node_id: nodeId, source: 'heuristic', validation, cost };
  }

  async deployBlueprint(payload: any): Promise<any> {
    // Simulated deploy: the NestJS control plane has no agent tunnel / IaC runner, so
    // return a well-shaped BlueprintDeployResponse describing a simulated success.
    const target = this.coerceTarget(payload?.target);
    const nodeId: string | null = payload?.node_id ?? null;
    const blueprint: InfraBlueprint | null = payload?.blueprint ?? null;
    const mode = target === 'local_node' ? 'homelab_docker' : 'iac';
    const serviceLinks =
      blueprint?.services?.map((s) => ({
        name: s.name,
        url:
          s.ports && s.ports.length > 0
            ? `http://localhost:${s.ports[0].host_port}`
            : null,
      })) ?? [];
    const steps = [
      { name: 'validate', ok: true, detail: 'Blueprint validated' },
      { name: 'plan', ok: true, detail: 'Deployment plan resolved' },
      { name: 'apply', ok: true, detail: 'Simulated apply complete' },
    ];
    return {
      deployment_id: randomUUID(),
      target,
      mode,
      node_id: nodeId,
      node_name: null,
      ok: true,
      steps,
      logs: ['Deploy started', 'Simulated deploy complete'],
      workspace_id: null,
      view_path: null,
      services: serviceLinks,
    };
  }

  async refineAnsible(payload: any): Promise<any> {
    // Heuristic Ansible refinement (Gemini unavailable): return the supplied files
    // unchanged with a summary, matching AnsibleRefineResponse.
    const files = Array.isArray(payload?.files) ? payload.files : [];
    return {
      files,
      summary: 'Heuristic pass: no automated changes applied (Gemini not configured).',
      source: 'heuristic',
      gemini_configured: this.geminiConfigured(),
    };
  }
}
