import type {
  AnsibleConfig,
  ContainerServiceItem,
  FrameworkOption,
} from '~/types/provisioning'
import type { ScaffoldTarget } from '~/utils/workspaceRepoScaffold'

/** Unique framework stacks from workspace services (order preserved). */
export function frameworksFromContainerServices(
  services: ContainerServiceItem[] | null | undefined,
): FrameworkOption[] {
  const out: FrameworkOption[] = []
  const seen = new Set<string>()
  for (const svc of services || []) {
    const stack = (svc.stack || '').trim() as FrameworkOption
    if (!stack || seen.has(stack)) continue
    seen.add(stack)
    out.push(stack)
  }
  return out
}

/**
 * Client-side Ansible tree under ``infra/ansible`` (matches API layout).
 * Full roles are enriched by the control plane on provision; this gives the IDE
 * a usable tree as soon as the user enables Ansible.
 */
export function buildAnsibleScaffold(
  workspaceName: string,
  config: AnsibleConfig,
): ScaffoldTarget[] {
  const name = workspaceName.trim() || 'launchpad-workspace'
  const group = config.inventory_group || 'app_servers'
  const hosts = (config.hosts || '127.0.0.1')
    .split(/[\n,]+/)
    .map((h) => h.trim())
    .filter(Boolean)
  const hostBlock = hosts.map((h) => `        ${h}:`).join('\n') || '        127.0.0.1:'
  const keyLine = config.ssh_private_key_path
    ? `        ansible_ssh_private_key_file: ${config.ssh_private_key_path}\n`
    : ''
  const packages = (config.packages || []).map((p) => `  - ${p}`).join('\n') || '  []'
  const ufw = (config.ufw_allow_ports || [22]).map((p) => `  - ${p}`).join('\n')
  const hostname = config.hostname || name

  return [
    {
      path: 'infra/ansible/ansible.cfg',
      content: [
        '[defaults]',
        'inventory = inventory/hosts.yml',
        'roles_path = roles',
        'host_key_checking = False',
        'retry_files_enabled = False',
        'stdout_callback = yaml',
        'interpreter_python = auto_silent',
        'forks = 20',
        '',
        '[privilege_escalation]',
        `become = ${config.become ? 'True' : 'False'}`,
        `become_user = ${config.become_user || 'root'}`,
        'become_method = sudo',
        '',
        '[ssh_connection]',
        'pipelining = True',
        'control_path = %(directory)s/%%h-%%r',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/inventory/hosts.yml',
      content: [
        'all:',
        '  children:',
        `    ${group}:`,
        '      hosts:',
        hostBlock,
        '      vars:',
        `        ansible_user: ${config.ssh_user || 'ubuntu'}`,
        `        ansible_port: ${config.ssh_port || 22}`,
        keyLine,
        `        ansible_python_interpreter: ${config.python_interpreter || 'auto'}`,
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/group_vars/all.yml',
      content: [
        `# Generated by Launchpad for workspace \`${name}\``,
        `launchpad_workspace: ${name}`,
        `target_hostname: ${hostname}`,
        `system_timezone: ${config.timezone || 'UTC'}`,
        'common_packages:',
        packages,
        `install_docker: ${config.install_docker}`,
        `install_compose_plugin: ${config.install_compose_plugin}`,
        `enable_ufw: ${config.enable_ufw}`,
        'ufw_allow_ports:',
        ufw,
        `enable_fail2ban: ${config.enable_fail2ban}`,
        `enable_unattended_upgrades: ${config.enable_unattended_upgrades}`,
        `create_deploy_user: ${config.create_deploy_user}`,
        `deploy_user: ${config.deploy_user || 'deploy'}`,
        `app_deploy_mode: ${config.app_deploy_mode || 'docker_run'}`,
        `app_dir: ${config.app_dir || '/opt/launchpad/app'}`,
        `app_listen_port: ${config.app_listen_port || 8080}`,
        `sync_workspace: ${config.sync_workspace}`,
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/playbooks/site.yml',
      content: [
        `---`,
        `# Site playbook for ${name}`,
        `- name: Bootstrap and deploy Launchpad workspace host`,
        `  hosts: ${group}`,
        '  become: true',
        '  roles:',
        '    - role: common',
        '    - role: docker',
        '      when: install_docker | default(true)',
        '    - role: hardening',
        '    - role: app',
        '      when: app_deploy_mode | default("docker_run") != "none"',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/requirements.yml',
      content: [
        '---',
        'collections:',
        '  - name: community.general',
        '  - name: community.docker',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/roles/common/tasks/main.yml',
      content: [
        '---',
        '- name: Ensure common packages',
        '  ansible.builtin.package:',
        '    name: "{{ common_packages }}"',
        '    state: present',
        '',
        '- name: Set timezone',
        '  community.general.timezone:',
        '    name: "{{ system_timezone }}"',
        '  when: system_timezone is defined',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/roles/docker/tasks/main.yml',
      content: [
        '---',
        '- name: Install Docker (placeholder - filled by control plane on provision)',
        '  ansible.builtin.debug:',
        '    msg: "Docker install role - see control-plane scaffold for distro-specific tasks"',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/roles/hardening/tasks/main.yml',
      content: [
        '---',
        '- name: Hardening placeholders (UFW / fail2ban / unattended)',
        '  ansible.builtin.debug:',
        '    msg: "Hardening role - expanded by control plane when enabled"',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/roles/app/tasks/main.yml',
      content: [
        '---',
        '- name: Ensure app directory',
        '  ansible.builtin.file:',
        '    path: "{{ app_dir }}"',
        '    state: directory',
        '    mode: "0755"',
        '',
        '- name: App deploy mode',
        '  ansible.builtin.debug:',
        '    msg: "Deploy via {{ app_deploy_mode }} on port {{ app_listen_port }}"',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/README.md',
      content: [
        `# Ansible - ${name}`,
        '',
        'Host configuration under `infra/ansible`.',
        '',
        '```bash',
        'cd infra/ansible',
        'ansible-galaxy collection install -r requirements.yml',
        'ansible-playbook playbooks/site.yml --check',
        'ansible-playbook playbooks/site.yml',
        '```',
        '',
        'Edit inventory, group_vars, and playbooks in the workspace IDE or the Ansible Advanced tab.',
        '',
      ].join('\n'),
    },
  ]
}
