import type {
  AnsibleConfig,
  ContainerServiceItem,
  FrameworkOption,
} from '~/types/provisioning'
import type { ScaffoldTarget } from '~/utils/workspaceRepoScaffold'

/** Unique framework stacks from workspace services (order preserved). */
export function frameworksFromContainerServices(
  services: ContainerServiceItem[] | null | undefined,
): FrameworkOption[] {
  const out: FrameworkOption[] = []
  const seen = new Set<string>()
  for (const svc of services || []) {
    const stack = (svc.stack || '').trim() as FrameworkOption
    if (!stack || seen.has(stack)) continue
    seen.add(stack)
    out.push(stack)
  }
  return out
}

/**
 * Client-side Ansible tree under ``infra/ansible`` (matches API layout).
 * Full roles are enriched by the control plane on provision; this gives the IDE
 * a usable tree as soon as the user enables Ansible.
 */
export function buildAnsibleScaffold(
  workspaceName: string,
  config: AnsibleConfig,
): ScaffoldTarget[] {
  const name = workspaceName.trim() || 'launchpad-workspace'
  const group = config.inventory_group || 'app_servers'
  const hosts = (config.hosts || '127.0.0.1')
    .split(/[\n,]+/)
    .map((h) => h.trim())
    .filter(Boolean)
  const hostBlock = hosts.map((h) => `        ${h}:`).join('\n') || '        127.0.0.1:'
  const keyLine = config.ssh_private_key_path
    ? `        ansible_ssh_private_key_file: ${config.ssh_private_key_path}\n`
    : ''
  const packages = (config.packages || []).map((p) => `  - ${p}`).join('\n') || '  []'
  const ufw = (config.ufw_allow_ports || [22]).map((p) => `  - ${p}`).join('\n')
  const hostname = config.hostname || name

  return [
    {
      path: 'infra/ansible/ansible.cfg',
      content: [
        '[defaults]',
        'inventory = inventory/hosts.yml',
        'roles_path = roles',
        'host_key_checking = False',
        'retry_files_enabled = False',
        'stdout_callback = yaml',
        'interpreter_python = auto_silent',
        'forks = 20',
        '',
        '[privilege_escalation]',
        `become = ${config.become ? 'True' : 'False'}`,
        `become_user = ${config.become_user || 'root'}`,
        'become_method = sudo',
        '',
        '[ssh_connection]',
        'pipelining = True',
        'control_path = %(directory)s/%%h-%%r',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/inventory/hosts.yml',
      content: [
        'all:',
        '  children:',
        `    ${group}:`,
        '      hosts:',
        hostBlock,
        '      vars:',
        `        ansible_user: ${config.ssh_user || 'ubuntu'}`,
        `        ansible_port: ${config.ssh_port || 22}`,
        keyLine,
        `        ansible_python_interpreter: ${config.python_interpreter || 'auto'}`,
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/group_vars/all.yml',
      content: [
        `# Generated by Launchpad for workspace \`${name}\``,
        `launchpad_workspace: ${name}`,
        `target_hostname: ${hostname}`,
        `system_timezone: ${config.timezone || 'UTC'}`,
        'common_packages:',
        packages,
        `install_docker: ${config.install_docker}`,
        `install_compose_plugin: ${config.install_compose_plugin}`,
        `enable_ufw: ${config.enable_ufw}`,
        'ufw_allow_ports:',
        ufw,
        `enable_fail2ban: ${config.enable_fail2ban}`,
        `enable_unattended_upgrades: ${config.enable_unattended_upgrades}`,
        `create_deploy_user: ${config.create_deploy_user}`,
        `deploy_user: ${config.deploy_user || 'deploy'}`,
        `app_deploy_mode: ${config.app_deploy_mode || 'docker_run'}`,
        `app_dir: ${config.app_dir || '/opt/launchpad/app'}`,
        `app_listen_port: ${config.app_listen_port || 8080}`,
        `reverse_proxy: ${config.reverse_proxy || 'none'}`,
        `app_start_command: ${JSON.stringify(config.app_start_command || 'npm start')}`,
        `sync_workspace: ${config.sync_workspace}`,
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/playbooks/site.yml',
      content: [
        `---`,
        `# Site playbook for ${name}`,
        `# app_deploy_mode=${config.app_deploy_mode || 'docker_run'} reverse_proxy=${config.reverse_proxy || 'none'}`,
        `- name: Bootstrap and deploy Launchpad workspace host`,
        `  hosts: ${group}`,
        '  become: true',
        '  roles:',
        '    - role: common',
        '    - role: docker',
        '      when: install_docker | default(true)',
        '    - role: hardening',
        '    - role: app',
        '      when: app_deploy_mode | default("docker_run") != "none"',
        '    - role: reverse_proxy',
        '      when: reverse_proxy | default("none") != "none"',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/requirements.yml',
      content: [
        '---',
        'collections:',
        '  - name: community.general',
        '  - name: community.docker',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/roles/common/tasks/main.yml',
      content: [
        '---',
        '- name: Ensure common packages',
        '  ansible.builtin.package:',
        '    name: "{{ common_packages }}"',
        '    state: present',
        '',
        '- name: Set timezone',
        '  community.general.timezone:',
        '    name: "{{ system_timezone }}"',
        '  when: system_timezone is defined',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/roles/docker/tasks/main.yml',
      content: [
        '---',
        '- name: Install Docker (placeholder - filled by control plane on provision)',
        '  ansible.builtin.debug:',
        '    msg: "Docker install role - see control-plane scaffold for distro-specific tasks"',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/roles/hardening/tasks/main.yml',
      content: [
        '---',
        '- name: Hardening placeholders (UFW / fail2ban / unattended)',
        '  ansible.builtin.debug:',
        '    msg: "Hardening role - expanded by control plane when enabled"',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/roles/app/tasks/main.yml',
      content: [
        '---',
        '- name: Ensure app directory',
        '  ansible.builtin.file:',
        '    path: "{{ app_dir }}"',
        '    state: directory',
        '    mode: "0755"',
        '    owner: "{{ deploy_user | default(\'deploy\') }}"',
        '',
        '- name: App deploy mode banner',
        '  ansible.builtin.debug:',
        '    msg: "Deploy via {{ app_deploy_mode }} on port {{ app_listen_port }} (proxy={{ reverse_proxy | default(\'none\') }})"',
        '',
        '- name: Install PM2 globally',
        '  community.general.npm:',
        '    name: pm2',
        '    global: true',
        '    state: present',
        '  when: app_deploy_mode == "pm2"',
        '',
        '- name: Start / reload PM2 ecosystem',
        '  ansible.builtin.command:',
        '    cmd: pm2 startOrReload ecosystem.config.cjs --update-env',
        '    chdir: "{{ app_dir }}"',
        '  when: app_deploy_mode == "pm2"',
        '',
        '- name: Persist PM2 process list',
        '  ansible.builtin.command:',
        '    cmd: pm2 save',
        '  when: app_deploy_mode == "pm2"',
        '',
        '- name: Install systemd unit for native app',
        '  ansible.builtin.copy:',
        '    dest: "/etc/systemd/system/{{ launchpad_workspace }}.service"',
        '    mode: "0644"',
        '    content: |',
        '      [Unit]',
        '      Description=Launchpad {{ launchpad_workspace }}',
        '      After=network-online.target',
        '      Wants=network-online.target',
        '',
        '      [Service]',
        '      Type=simple',
        '      User={{ deploy_user | default("deploy") }}',
        '      WorkingDirectory={{ app_dir }}',
        '      Environment=PORT={{ app_listen_port }}',
        '      Environment=HOST=0.0.0.0',
        '      EnvironmentFile=-{{ app_dir }}/.env',
        '      ExecStart=/bin/bash -lc \'{{ app_start_command | default("npm start") }}\'',
        '      Restart=on-failure',
        '',
        '      [Install]',
        '      WantedBy=multi-user.target',
        '  when: app_deploy_mode == "systemd"',
        '',
        '- name: Enable and start systemd app unit',
        '  ansible.builtin.systemd:',
        '    name: "{{ launchpad_workspace }}.service"',
        '    enabled: true',
        '    state: started',
        '    daemon_reload: true',
        '  when: app_deploy_mode == "systemd"',
        '',
        '- name: Run app container (docker_run)',
        '  ansible.builtin.debug:',
        '    msg: "docker_run mode - control plane expands image + ports on provision"',
        '  when: app_deploy_mode == "docker_run"',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/roles/reverse_proxy/tasks/main.yml',
      content: [
        '---',
        '- name: Install nginx',
        '  ansible.builtin.package:',
        '    name: nginx',
        '    state: present',
        '  when: reverse_proxy == "nginx"',
        '',
        '- name: Configure nginx reverse proxy',
        '  ansible.builtin.copy:',
        '    dest: /etc/nginx/sites-available/launchpad-app.conf',
        '    mode: "0644"',
        '    content: |',
        '      server {',
        '        listen 80;',
        '        server_name _;',
        '        location / {',
        '          proxy_pass http://127.0.0.1:{{ app_listen_port }};',
        '          proxy_http_version 1.1;',
        '          proxy_set_header Host $host;',
        '          proxy_set_header X-Real-IP $remote_addr;',
        '          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
        '          proxy_set_header X-Forwarded-Proto $scheme;',
        '        }',
        '      }',
        '  when: reverse_proxy == "nginx"',
        '',
        '- name: Enable nginx site',
        '  ansible.builtin.file:',
        '    src: /etc/nginx/sites-available/launchpad-app.conf',
        '    dest: /etc/nginx/sites-enabled/launchpad-app.conf',
        '    state: link',
        '  when: reverse_proxy == "nginx"',
        '',
        '- name: Reload nginx',
        '  ansible.builtin.service:',
        '    name: nginx',
        '    state: reloaded',
        '    enabled: true',
        '  when: reverse_proxy == "nginx"',
        '',
        '- name: Install Caddy',
        '  ansible.builtin.debug:',
        '    msg: "Install Caddy from official packages, then use infra/instance/Caddyfile"',
        '  when: reverse_proxy == "caddy"',
        '',
      ].join('\n'),
    },
    {
      path: 'infra/ansible/README.md',
      content: [
        `# Ansible - ${name}`,
        '',
        `Process strategy / app mode: \`${config.app_deploy_mode || 'docker_run'}\``,
        `Reverse proxy: \`${config.reverse_proxy || 'none'}\``,
        '',
        'Host configuration under `infra/ansible`.',
        '',
        '```bash',
        'cd infra/ansible',
        'ansible-galaxy collection install -r requirements.yml',
        'ansible-playbook playbooks/site.yml --check',
        'ansible-playbook playbooks/site.yml',
        '```',
        '',
        'Edit inventory, group_vars, and playbooks in the workspace IDE, the Ansible Advanced tab, or use **Update with AI**.',
        '',
      ].join('\n'),
    },
  ]
}
