/** Material Symbols glyphs for cloud / IaaS / PaaS plugins. */
export interface PluginCloudIcon {
  glyph: string
  label: string
}

export const PLUGIN_CLOUD_ICONS: PluginCloudIcon[] = [
  { glyph: 'cloud', label: 'Cloud' },
  { glyph: 'cloud_off', label: 'Cloud off' },
  { glyph: 'cloud_queue', label: 'Azure' },
  { glyph: 'cloud_sync', label: 'GCP' },
  { glyph: 'cloud_upload', label: 'AWS' },
  { glyph: 'cloud_download', label: 'S3 / Object storage' },
  { glyph: 'cloud_done', label: 'Ready' },
  { glyph: 'cloud_circle', label: 'Cloud circle' },
  { glyph: 'filter_drama', label: 'Generic cloud' },
  { glyph: 'wb_cloudy', label: 'Cloudy' },
  { glyph: 'partly_cloudy_day', label: 'Partly cloudy' },
  { glyph: 'partly_cloudy_night', label: 'Night cloud' },
  { glyph: 'foggy', label: 'Fog / mist' },
  { glyph: 'thunderstorm', label: 'Storm' },
  { glyph: 'cyclone', label: 'Cloudflare' },
  { glyph: 'air', label: 'Wind / airflow' },
  { glyph: 'water_drop', label: 'DigitalOcean' },
  { glyph: 'waves', label: 'Ocean / droplets' },
  { glyph: 'water', label: 'Water' },
  { glyph: 'tsunami', label: 'Wave' },
  { glyph: 'dns', label: 'Hetzner / DNS' },
  { glyph: 'hub', label: 'Kubernetes' },
  { glyph: 'device_hub', label: 'Cluster' },
  { glyph: 'account_tree', label: 'Terraform / Pulumi' },
  { glyph: 'lan', label: 'Network / VPC' },
  { glyph: 'router', label: 'Router / gateway' },
  { glyph: 'settings_ethernet', label: 'Ethernet' },
  { glyph: 'settings_input_hdmi', label: 'Interconnect' },
  { glyph: 'cable', label: 'Cable' },
  { glyph: 'public', label: 'Public internet' },
  { glyph: 'language', label: 'Global CDN' },
  { glyph: 'travel_explore', label: 'Edge' },
  { glyph: 'explore', label: 'Discover' },
  { glyph: 'south_america', label: 'Regions' },
  { glyph: 'public_off', label: 'Private network' },
  { glyph: 'rocket_launch', label: 'Railway / launch' },
  { glyph: 'rocket', label: 'Deploy' },
  { glyph: 'flight_takeoff', label: 'Fly.io' },
  { glyph: 'flight', label: 'Fly' },
  { glyph: 'train', label: 'Railway' },
  { glyph: 'directions_subway', label: 'Pipeline' },
  { glyph: 'change_history', label: 'Vercel' },
  { glyph: 'web', label: 'Netlify / web' },
  { glyph: 'web_asset', label: 'Web asset' },
  { glyph: 'deployed_code', label: 'Containers / ECS' },
  { glyph: 'view_in_ar', label: 'Containers' },
  { glyph: 'inventory_2', label: 'Package / registry' },
  { glyph: 'package_2', label: 'Helm / packages' },
  { glyph: 'layers', label: 'OpenStack / stacks' },
  { glyph: 'grid_view', label: 'Scaleway' },
  { glyph: 'grid_on', label: 'Grid' },
  { glyph: 'storage', label: 'Block storage' },
  { glyph: 'database', label: 'Database' },
  { glyph: 'hard_drive', label: 'Volume' },
  { glyph: 'sd_card', label: 'Local disk' },
  { glyph: 'memory', label: 'Compute / RAM' },
  { glyph: 'memory_alt', label: 'Cache / Redis' },
  { glyph: 'developer_board', label: 'Bare metal' },
  { glyph: 'terminal', label: 'CLI / SSH' },
  { glyph: 'computer', label: 'VM' },
  { glyph: 'desktop_windows', label: 'VMware' },
  { glyph: 'desktop_mac', label: 'Mac host' },
  { glyph: 'laptop', label: 'Workstation' },
  { glyph: 'laptop_windows', label: 'Windows VM' },
  { glyph: 'bolt', label: 'Vultr / Neon' },
  { glyph: 'electric_bolt', label: 'Serverless' },
  { glyph: 'offline_bolt', label: 'Burst' },
  { glyph: 'functions', label: 'Cloud Functions' },
  { glyph: 'directions_run', label: 'Cloud Run' },
  { glyph: 'sailing', label: 'Fargate' },
  { glyph: 'play_arrow', label: 'Ansible' },
  { glyph: 'schema', label: 'Schema / graph' },
  { glyph: 'polyline', label: 'Graph' },
  { glyph: 'dataset', label: 'Data warehouse' },
  { glyph: 'table_chart', label: 'Supabase' },
  { glyph: 'table_rows', label: 'Tables' },
  { glyph: 'analytics', label: 'Databricks' },
  { glyph: 'monitoring', label: 'Observability' },
  { glyph: 'query_stats', label: 'Metrics' },
  { glyph: 'ssid_chart', label: 'Time series' },
  { glyph: 'show_chart', label: 'Charts' },
  { glyph: 'insights', label: 'Insights' },
  { glyph: 'ac_unit', label: 'Snowflake' },
  { glyph: 'local_fire_department', label: 'Firebase' },
  { glyph: 'whatshot', label: 'Hot path' },
  { glyph: 'backup', label: 'Backup / B2' },
  { glyph: 'settings_backup_restore', label: 'Restore' },
  { glyph: 'vpn_lock', label: 'VPN' },
  { glyph: 'vpn_key', label: 'VPN key' },
  { glyph: 'lock', label: 'Vault / secrets' },
  { glyph: 'lock_open', label: 'Unlock' },
  { glyph: 'encrypted', label: 'KMS' },
  { glyph: 'security', label: 'Security' },
  { glyph: 'shield', label: 'WAF' },
  { glyph: 'verified_user', label: 'Verified' },
  { glyph: 'gpp_good', label: 'Compliance' },
  { glyph: 'policy', label: 'Policy' },
  { glyph: 'fingerprint', label: 'Identity' },
  { glyph: 'passkey', label: 'Auth' },
  { glyph: 'key', label: 'API keys' },
  { glyph: 'token', label: 'Tokens' },
  { glyph: 'badge', label: 'Okta / IAM' },
  { glyph: 'admin_panel_settings', label: 'Admin IAM' },
  { glyph: 'speed', label: 'Fastly' },
  { glyph: 'network_ping', label: 'Latency' },
  { glyph: 'network_check', label: 'Health check' },
  { glyph: 'cell_tower', label: 'Telecom' },
  { glyph: 'satellite_alt', label: 'Satellite / edge' },
  { glyph: 'wifi', label: 'Connectivity' },
  { glyph: 'wifi_tethering', label: 'Tether' },
  { glyph: 'share', label: 'Service mesh' },
  { glyph: 'workspaces', label: 'Nomad / workspaces' },
  { glyph: 'group_work', label: 'Work group' },
  { glyph: 'apartment', label: 'Enterprise' },
  { glyph: 'domain', label: 'Custom domain' },
  { glyph: 'corporate_fare', label: 'Organization' },
  { glyph: 'business', label: 'Business' },
  { glyph: 'apps', label: 'App platform' },
  { glyph: 'code', label: 'Git / source' },
  { glyph: 'merge', label: 'GitLab' },
  { glyph: 'fork_right', label: 'Fork' },
  { glyph: 'commit', label: 'Commit' },
  { glyph: 'difference', label: 'Diff' },
  { glyph: 'mail', label: 'Email / SES' },
  { glyph: 'outgoing_mail', label: 'Outbound mail' },
  { glyph: 'sms', label: 'Messaging' },
  { glyph: 'forum', label: 'Pub/Sub' },
  { glyph: 'chat', label: 'Chat' },
  { glyph: 'folder_managed', label: 'Managed files' },
  { glyph: 'folder_zip', label: 'Bundle' },
  { glyph: 'perm_media', label: 'Media / CDN' },
  { glyph: 'photo_library', label: 'Assets' },
  { glyph: 'unarchive', label: 'Artifacts' },
  { glyph: 'archive', label: 'Archive' },
  { glyph: 'radar', label: 'Discovery' },
  { glyph: 'podcasts', label: 'Streaming' },
  { glyph: 'stream', label: 'Stream' },
  { glyph: 'host', label: 'Host / node' },
  { glyph: 'http', label: 'HTTP' },
  { glyph: 'https', label: 'HTTPS' },
  { glyph: 'api', label: 'API gateway' },
  { glyph: 'webhook', label: 'Webhooks' },
  { glyph: 'queue', label: 'Queue / SQS' },
  { glyph: 'sync_alt', label: 'Sync' },
  { glyph: 'swap_horiz', label: 'Load balancer' },
  { glyph: 'alt_route', label: 'Routing' },
  { glyph: 'precision_manufacturing', label: 'Jobs' },
  { glyph: 'schedule', label: 'Cron / scheduler' },
  { glyph: 'timer', label: 'TTL' },
  { glyph: 'hourglass_empty', label: 'Timeout' },
  { glyph: 'neurology', label: 'AI / ML' },
  { glyph: 'smart_toy', label: 'Agents' },
  { glyph: 'model_training', label: 'Training' },
  { glyph: 'psychology', label: 'Inference' },
  { glyph: 'blur_on', label: 'GPU' },
  { glyph: 'center_focus_strong', label: 'Target' },
  { glyph: 'hexagon', label: 'Honeycomb' },
]

export function pluginIconLabel(glyph: string): string {
  return PLUGIN_CLOUD_ICONS.find((item) => item.glyph === glyph)?.label ?? glyph
}

export function filterPluginCloudIcons(query: string): PluginCloudIcon[] {
  const q = query.trim().toLowerCase()
  if (!q) return PLUGIN_CLOUD_ICONS
  return PLUGIN_CLOUD_ICONS.filter(
    (item) => item.label.toLowerCase().includes(q) || item.glyph.toLowerCase().includes(q),
  )
}
