"""Best-practice Ansible tree for VM / Compose host provisioning."""

from __future__ import annotations

import json
from pathlib import Path

from app.schemas.cloud import (
    AnsibleAppDeployMode,
    AnsibleConfig,
    InstanceReverseProxy,
    WorkspaceRuntimeMode,
)

ANSIBLE_ROOT = Path("infra") / "ansible"


def write_ansible_scaffold(
    workspace_dir: Path,
    *,
    name: str,
    config: AnsibleConfig,
    runtime_mode: WorkspaceRuntimeMode,
    listen_port: int | None = None,
) -> list[str]:
    """Write ``infra/ansible`` inventory, playbooks, and roles from wizard options."""
    cfg = config
    if listen_port and listen_port != cfg.app_listen_port:
        cfg = cfg.model_copy(update={"app_listen_port": listen_port})

    hosts = _parse_hosts(cfg.hosts)
    if not hosts:
        hosts = ["127.0.0.1"]

    written: list[str] = []

    def _write(relative: Path, content: str) -> None:
        path = workspace_dir / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(str(relative).replace("\\", "/"))

    group = cfg.inventory_group or "app_servers"
    host_lines = "\n".join(f"        {h}:" for h in hosts)
    key_line = (
        f"        ansible_ssh_private_key_file: {cfg.ssh_private_key_path}\n"
        if cfg.ssh_private_key_path
        else ""
    )
    vault_line = (
        f"vault_password_file = {cfg.vault_password_file}\n"
        if cfg.use_vault and cfg.vault_password_file
        else ""
    )

    _write(
        ANSIBLE_ROOT / "ansible.cfg",
        "[defaults]\n"
        "inventory = inventory/hosts.yml\n"
        "roles_path = roles\n"
        "host_key_checking = False\n"
        "retry_files_enabled = False\n"
        "stdout_callback = yaml\n"
        "interpreter_python = auto_silent\n"
        "forks = 20\n"
        f"{vault_line}"
        "\n"
        "[privilege_escalation]\n"
        f"become = {'True' if cfg.become else 'False'}\n"
        f"become_user = {cfg.become_user}\n"
        "become_method = sudo\n"
        "\n"
        "[ssh_connection]\n"
        "pipelining = True\n"
        "control_path = %(directory)s/%%h-%%r\n",
    )

    _write(
        ANSIBLE_ROOT / "inventory" / "hosts.yml",
        "all:\n"
        "  children:\n"
        f"    {group}:\n"
        "      hosts:\n"
        f"{host_lines}\n"
        "      vars:\n"
        f"        ansible_user: {cfg.ssh_user}\n"
        f"        ansible_port: {cfg.ssh_port}\n"
        f"{key_line}"
        f"        ansible_python_interpreter: {cfg.python_interpreter}\n",
    )

    packages_yaml = "\n".join(f"  - {p}" for p in cfg.packages) or "  []"
    ufw_ports = "\n".join(f"  - {p}" for p in cfg.ufw_allow_ports) or "  - 22"
    groups_yaml = "\n".join(f"  - {g}" for g in cfg.deploy_user_groups) or "  - docker"
    hostname = cfg.hostname or name
    app_mode = cfg.app_deploy_mode.value

    _write(
        ANSIBLE_ROOT / "group_vars" / "all.yml",
        f"# Generated by Launchpad for workspace `{name}` ({runtime_mode.value})\n"
        f"launchpad_workspace: {name}\n"
        f"launchpad_runtime_mode: {runtime_mode.value}\n"
        f"target_hostname: {hostname}\n"
        f"system_timezone: {cfg.timezone}\n"
        "common_packages:\n"
        f"{packages_yaml}\n"
        f"install_docker: {str(cfg.install_docker).lower()}\n"
        f"install_compose_plugin: {str(cfg.install_compose_plugin).lower()}\n"
        f"enable_ufw: {str(cfg.enable_ufw).lower()}\n"
        "ufw_allow_ports:\n"
        f"{ufw_ports}\n"
        f"enable_fail2ban: {str(cfg.enable_fail2ban).lower()}\n"
        f"enable_unattended_upgrades: {str(cfg.enable_unattended_upgrades).lower()}\n"
        f"create_deploy_user: {str(cfg.create_deploy_user).lower()}\n"
        f"deploy_user: {cfg.deploy_user}\n"
        "deploy_user_groups:\n"
        f"{groups_yaml}\n"
        f"app_deploy_mode: {app_mode}\n"
        f"app_dir: {cfg.app_dir}\n"
        f"app_listen_port: {cfg.app_listen_port}\n"
        f"reverse_proxy: {cfg.reverse_proxy.value}\n"
        f"app_start_command: {json.dumps(cfg.app_start_command or 'npm start')}\n"
        f"sync_workspace: {str(cfg.sync_workspace).lower()}\n"
        f"set_hostname: {str(cfg.set_hostname).lower()}\n",
    )

    roles: list[str] = ["common"]
    if cfg.install_docker:
        roles.append("docker")
    if cfg.enable_ufw or cfg.enable_fail2ban or cfg.enable_unattended_upgrades:
        roles.append("hardening")
    if cfg.create_deploy_user:
        roles.append("users")
    if cfg.app_deploy_mode != AnsibleAppDeployMode.NONE:
        roles.append("app")
    if cfg.reverse_proxy != InstanceReverseProxy.NONE:
        roles.append("reverse_proxy")

    role_lines = "\n".join(f"      - {r}" for r in roles)
    _write(
        ANSIBLE_ROOT / "playbooks" / "site.yml",
        "---\n"
        f"# app_deploy_mode={app_mode} reverse_proxy={cfg.reverse_proxy.value}\n"
        f"- name: Provision Launchpad host for {name}\n"
        f"  hosts: {group}\n"
        "  become: true\n"
        "  gather_facts: true\n"
        "  roles:\n"
        f"{role_lines}\n",
    )

    _write_role_common(_write)
    if cfg.install_docker:
        _write_role_docker(_write)
    if "hardening" in roles:
        _write_role_hardening(_write)
    if cfg.create_deploy_user:
        _write_role_users(_write)
    if cfg.app_deploy_mode != AnsibleAppDeployMode.NONE:
        _write_role_app(_write)
    if cfg.reverse_proxy != InstanceReverseProxy.NONE:
        _write_role_reverse_proxy(_write)

    _write(
        ANSIBLE_ROOT / "requirements.yml",
        "---\n"
        "collections:\n"
        "  - name: community.general\n"
        "  - name: community.docker\n",
    )

    _write(
        ANSIBLE_ROOT / "README.md",
        f"# Ansible - {name}\n\n"
        "Best-practice host provisioning for Launchpad **running instance** / "
        "**Docker Compose** targets.\n\n"
        "## Prerequisites\n\n"
        "- Ansible 2.15+\n"
        "- SSH access to inventory hosts\n"
        "- Optional: `ansible-galaxy collection install community.general community.docker`\n\n"
        "## Run\n\n"
        "```bash\n"
        "cd infra/ansible\n"
        "ansible-playbook playbooks/site.yml --check   # dry-run\n"
        "ansible-playbook playbooks/site.yml\n"
        "```\n\n"
        "Limit to one host:\n\n"
        "```bash\n"
        f"ansible-playbook playbooks/site.yml --limit '{hosts[0]}'\n"
        "```\n\n"
        "Tags (when added to tasks): `common`, `docker`, `firewall`, `app`.\n"
        "Never commit vault passwords or private keys.\n",
    )

    _write(
        ANSIBLE_ROOT / "scripts" / "run.sh",
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        "cd \"$(dirname \"$0\")/..\"\n"
        "ansible-playbook playbooks/site.yml \"$@\"\n",
    )

    return written


def _parse_hosts(raw: str) -> list[str]:
    parts: list[str] = []
    for chunk in raw.replace(",", "\n").splitlines():
        host = chunk.strip()
        if host and host not in parts:
            parts.append(host)
    return parts


def _write_role_common(write) -> None:
    write(
        ANSIBLE_ROOT / "roles" / "common" / "tasks" / "main.yml",
        "---\n"
        "- name: Set hostname\n"
        "  ansible.builtin.hostname:\n"
        "    name: \"{{ target_hostname }}\"\n"
        "  when: set_hostname | bool\n"
        "  tags: [common]\n\n"
        "- name: Set timezone\n"
        "  community.general.timezone:\n"
        "    name: \"{{ system_timezone }}\"\n"
        "  tags: [common]\n\n"
        "- name: Update apt cache\n"
        "  ansible.builtin.apt:\n"
        "    update_cache: true\n"
        "    cache_valid_time: 3600\n"
        "  when: ansible_os_family == 'Debian'\n"
        "  tags: [common]\n\n"
        "- name: Install baseline packages\n"
        "  ansible.builtin.package:\n"
        "    name: \"{{ common_packages }}\"\n"
        "    state: present\n"
        "  tags: [common]\n",
    )


def _write_role_docker(write) -> None:
    write(
        ANSIBLE_ROOT / "roles" / "docker" / "tasks" / "main.yml",
        "---\n"
        "- name: Install Docker prerequisites\n"
        "  ansible.builtin.apt:\n"
        "    name: [ca-certificates, curl, gnupg]\n"
        "    state: present\n"
        "  when: ansible_os_family == 'Debian'\n"
        "  tags: [docker]\n\n"
        "- name: Add Docker apt key\n"
        "  ansible.builtin.get_url:\n"
        "    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg\n"
        "    dest: /etc/apt/keyrings/docker.asc\n"
        "    mode: '0644'\n"
        "  when: ansible_os_family == 'Debian'\n"
        "  tags: [docker]\n\n"
        "- name: Add Docker apt repository\n"
        "  ansible.builtin.apt_repository:\n"
        "    repo: >-\n"
        "      deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') }}\n"
        "      signed-by=/etc/apt/keyrings/docker.asc]\n"
        "      https://download.docker.com/linux/{{ ansible_distribution | lower }}\n"
        "      {{ ansible_distribution_release }} stable\n"
        "    state: present\n"
        "  when: ansible_os_family == 'Debian'\n"
        "  tags: [docker]\n\n"
        "- name: Install Docker Engine packages\n"
        "  ansible.builtin.apt:\n"
        "    name: \"{{ docker_packages }}\"\n"
        "    state: present\n"
        "    update_cache: true\n"
        "  vars:\n"
        "    docker_packages: >-\n"
        "      {{ ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin']\n"
        "         + (['docker-compose-plugin'] if install_compose_plugin else []) }}\n"
        "  when: ansible_os_family == 'Debian'\n"
        "  tags: [docker]\n\n"
        "- name: Ensure Docker service is enabled\n"
        "  ansible.builtin.service:\n"
        "    name: docker\n"
        "    state: started\n"
        "    enabled: true\n"
        "  tags: [docker]\n",
    )


def _write_role_hardening(write) -> None:
    write(
        ANSIBLE_ROOT / "roles" / "hardening" / "tasks" / "main.yml",
        "---\n"
        "- name: Install UFW\n"
        "  ansible.builtin.package:\n"
        "    name: ufw\n"
        "    state: present\n"
        "  when: enable_ufw | bool\n"
        "  tags: [firewall, hardening]\n\n"
        "- name: Allow UFW ports\n"
        "  community.general.ufw:\n"
        "    rule: allow\n"
        "    port: \"{{ item }}\"\n"
        "    proto: tcp\n"
        "  loop: \"{{ ufw_allow_ports }}\"\n"
        "  when: enable_ufw | bool\n"
        "  tags: [firewall, hardening]\n\n"
        "- name: Enable UFW\n"
        "  community.general.ufw:\n"
        "    state: enabled\n"
        "    policy: deny\n"
        "  when: enable_ufw | bool\n"
        "  tags: [firewall, hardening]\n\n"
        "- name: Install fail2ban\n"
        "  ansible.builtin.package:\n"
        "    name: fail2ban\n"
        "    state: present\n"
        "  when: enable_fail2ban | bool\n"
        "  tags: [hardening]\n\n"
        "- name: Enable fail2ban\n"
        "  ansible.builtin.service:\n"
        "    name: fail2ban\n"
        "    state: started\n"
        "    enabled: true\n"
        "  when: enable_fail2ban | bool\n"
        "  tags: [hardening]\n\n"
        "- name: Install unattended-upgrades\n"
        "  ansible.builtin.package:\n"
        "    name: unattended-upgrades\n"
        "    state: present\n"
        "  when: enable_unattended_upgrades | bool and ansible_os_family == 'Debian'\n"
        "  tags: [hardening]\n",
    )


def _write_role_users(write) -> None:
    write(
        ANSIBLE_ROOT / "roles" / "users" / "tasks" / "main.yml",
        "---\n"
        "- name: Create deploy user\n"
        "  ansible.builtin.user:\n"
        "    name: \"{{ deploy_user }}\"\n"
        "    groups: \"{{ deploy_user_groups }}\"\n"
        "    append: true\n"
        "    shell: /bin/bash\n"
        "    create_home: true\n"
        "  when: create_deploy_user | bool\n"
        "  tags: [users]\n\n"
        "- name: Allow deploy user passwordless sudo for docker\n"
        "  ansible.builtin.copy:\n"
        "    dest: \"/etc/sudoers.d/{{ deploy_user }}-docker\"\n"
        "    content: \"{{ deploy_user }} ALL=(ALL) NOPASSWD: /usr/bin/docker, /usr/bin/docker-compose\\n\"\n"
        "    mode: '0440'\n"
        "    validate: 'visudo -cf %s'\n"
        "  when: create_deploy_user | bool\n"
        "  tags: [users]\n",
    )


def _write_role_app(write) -> None:
    write(
        ANSIBLE_ROOT / "roles" / "app" / "tasks" / "main.yml",
        "---\n"
        "- name: Ensure application directory\n"
        "  ansible.builtin.file:\n"
        "    path: \"{{ app_dir }}\"\n"
        "    state: directory\n"
        "    owner: \"{{ deploy_user | default('root') }}\"\n"
        "    group: \"{{ deploy_user | default('root') }}\"\n"
        "    mode: '0755'\n"
        "  tags: [app]\n\n"
        "- name: Sync workspace sources to app_dir\n"
        "  ansible.builtin.copy:\n"
        "    src: \"{{ playbook_dir }}/../../../\"\n"
        "    dest: \"{{ app_dir }}/\"\n"
        "    owner: \"{{ deploy_user | default('root') }}\"\n"
        "    mode: preserve\n"
        "  when: sync_workspace | bool\n"
        "  tags: [app]\n\n"
        "- name: Build application image\n"
        "  community.docker.docker_image:\n"
        "    name: \"{{ launchpad_workspace }}-app\"\n"
        "    source: build\n"
        "    build:\n"
        "      path: \"{{ app_dir }}\"\n"
        "    force_source: true\n"
        "  when: app_deploy_mode == 'docker_run'\n"
        "  tags: [app]\n\n"
        "- name: Run application container\n"
        "  community.docker.docker_container:\n"
        "    name: \"{{ launchpad_workspace }}-app\"\n"
        "    image: \"{{ launchpad_workspace }}-app\"\n"
        "    state: started\n"
        "    restart_policy: unless-stopped\n"
        "    published_ports:\n"
        "      - \"{{ app_listen_port }}:{{ app_listen_port }}\"\n"
        "    env:\n"
        "      PORT: \"{{ app_listen_port }}\"\n"
        "  when: app_deploy_mode == 'docker_run'\n"
        "  tags: [app]\n\n"
        "- name: Start stack with Docker Compose\n"
        "  community.docker.docker_compose_v2:\n"
        "    project_src: \"{{ app_dir }}\"\n"
        "    state: present\n"
        "    build: always\n"
        "  when: app_deploy_mode == 'docker_compose'\n"
        "  tags: [app]\n\n"
        "- name: Install systemd unit for native app\n"
        "  ansible.builtin.copy:\n"
        "    dest: \"/etc/systemd/system/{{ launchpad_workspace }}.service\"\n"
        "    mode: '0644'\n"
        "    content: |\n"
        "      [Unit]\n"
        "      Description=Launchpad {{ launchpad_workspace }}\n"
        "      After=network-online.target\n"
        "      Wants=network-online.target\n"
        "\n"
        "      [Service]\n"
        "      Type=simple\n"
        "      User={{ deploy_user | default('root') }}\n"
        "      WorkingDirectory={{ app_dir }}\n"
        "      Environment=PORT={{ app_listen_port }}\n"
        "      Environment=HOST=0.0.0.0\n"
        "      EnvironmentFile=-{{ app_dir }}/.env\n"
        "      ExecStart=/bin/bash -lc '{{ app_start_command | default(\"npm start\") }}'\n"
        "      Restart=on-failure\n"
        "\n"
        "      [Install]\n"
        "      WantedBy=multi-user.target\n"
        "  when: app_deploy_mode == 'systemd'\n"
        "  tags: [app]\n\n"
        "- name: Enable and start systemd app unit\n"
        "  ansible.builtin.systemd:\n"
        "    name: \"{{ launchpad_workspace }}.service\"\n"
        "    enabled: true\n"
        "    state: started\n"
        "    daemon_reload: true\n"
        "  when: app_deploy_mode == 'systemd'\n"
        "  tags: [app]\n\n"
        "- name: Ensure PM2 is installed globally\n"
        "  community.general.npm:\n"
        "    name: pm2\n"
        "    global: true\n"
        "    state: present\n"
        "  when: app_deploy_mode == 'pm2'\n"
        "  tags: [app]\n\n"
        "- name: Start app with PM2 ecosystem\n"
        "  ansible.builtin.command:\n"
        "    cmd: pm2 start ecosystem.config.cjs\n"
        "    chdir: \"{{ app_dir }}\"\n"
        "  when: app_deploy_mode == 'pm2'\n"
        "  tags: [app]\n\n"
        "- name: Persist PM2 process list\n"
        "  ansible.builtin.command:\n"
        "    cmd: pm2 save\n"
        "  when: app_deploy_mode == 'pm2'\n"
        "  tags: [app]\n",
    )


def _write_role_reverse_proxy(write) -> None:
    write(
        ANSIBLE_ROOT / "roles" / "reverse_proxy" / "tasks" / "main.yml",
        "---\n"
        "- name: Install nginx\n"
        "  ansible.builtin.package:\n"
        "    name: nginx\n"
        "    state: present\n"
        "  when: reverse_proxy == 'nginx'\n"
        "  tags: [reverse_proxy]\n\n"
        "- name: Configure nginx reverse proxy\n"
        "  ansible.builtin.copy:\n"
        "    dest: /etc/nginx/sites-available/launchpad-app.conf\n"
        "    mode: '0644'\n"
        "    content: |\n"
        "      server {\n"
        "        listen 80;\n"
        "        server_name _;\n"
        "        location / {\n"
        "          proxy_pass http://127.0.0.1:{{ app_listen_port }};\n"
        "          proxy_http_version 1.1;\n"
        "          proxy_set_header Host $host;\n"
        "          proxy_set_header X-Real-IP $remote_addr;\n"
        "          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
        "          proxy_set_header X-Forwarded-Proto $scheme;\n"
        "        }\n"
        "      }\n"
        "  when: reverse_proxy == 'nginx'\n"
        "  tags: [reverse_proxy]\n\n"
        "- name: Enable nginx site\n"
        "  ansible.builtin.file:\n"
        "    src: /etc/nginx/sites-available/launchpad-app.conf\n"
        "    dest: /etc/nginx/sites-enabled/launchpad-app.conf\n"
        "    state: link\n"
        "  when: reverse_proxy == 'nginx'\n"
        "  tags: [reverse_proxy]\n\n"
        "- name: Reload nginx\n"
        "  ansible.builtin.service:\n"
        "    name: nginx\n"
        "    state: reloaded\n"
        "    enabled: true\n"
        "  when: reverse_proxy == 'nginx'\n"
        "  tags: [reverse_proxy]\n\n"
        "- name: Install Caddy package\n"
        "  ansible.builtin.debug:\n"
        "    msg: >-\n"
        "      Install Caddy from official packages, then apply infra/instance/Caddyfile\n"
        "      proxying to 127.0.0.1:{{ app_listen_port }}\n"
        "  when: reverse_proxy == 'caddy'\n"
        "  tags: [reverse_proxy]\n",
    )
