"""Write Makefile targets so terminal / CI / Launchpad share one cloud deploy path."""

from __future__ import annotations

from pathlib import Path

from app.schemas.cloud import IaCEngine


def write_cloud_deploy_makefile(
    workspace_dir: Path,
    *,
    engine: IaCEngine,
) -> list[str]:
    """Emit a root Makefile with cloud-up / configure / destroy targets."""
    if engine == IaCEngine.OPENTOFU:
        tf_cli = "tofu"
        tf_dir = "infra/terraform"
    elif engine == IaCEngine.TERRAFORM:
        tf_cli = "terraform"
        tf_dir = "infra/terraform"
    elif engine == IaCEngine.PULUMI:
        tf_cli = "pulumi"
        tf_dir = "infra/pulumi"
    else:
        tf_cli = "terraform"
        tf_dir = "infra/terraform"

    if engine == IaCEngine.PULUMI:
        apply_recipe = (
            f"\tcd {tf_dir} && pulumi up --yes --skip-preview --non-interactive\n"
        )
        destroy_recipe = (
            f"\tcd {tf_dir} && pulumi destroy --yes --skip-preview --non-interactive\n"
        )
        output_recipe = f"\tcd {tf_dir} && pulumi stack output --json\n"
    else:
        apply_recipe = (
            f"\tcd {tf_dir} && {tf_cli} init -input=false\n"
            f"\tcd {tf_dir} && {tf_cli} apply -auto-approve -input=false\n"
        )
        destroy_recipe = (
            f"\tcd {tf_dir} && {tf_cli} destroy -auto-approve -input=false\n"
        )
        output_recipe = f"\tcd {tf_dir} && {tf_cli} output -json\n"

    content = (
        "# Generated by Launchpad - portable cloud deploy (UI, CI, and terminal).\n"
        "# Usage:\n"
        "#   make cloud-up       # terraform/pulumi apply\n"
        "#   make configure      # ansible-playbook site.yml (VM hosts)\n"
        "#   make deploy         # cloud-up + configure\n"
        "#   make cloud-down     # destroy applied infra\n"
        "#   make outputs        # print IaC outputs (preview_url, public_ip, …)\n"
        "\n"
        ".PHONY: cloud-up configure deploy cloud-down outputs ansible-galaxy\n"
        "\n"
        "cloud-up:\n"
        f"{apply_recipe}"
        "\n"
        "ansible-galaxy:\n"
        "\t@if [ -f infra/ansible/requirements.yml ]; then \\\n"
        "\t  cd infra/ansible && ansible-galaxy collection install -r requirements.yml -p collections; \\\n"
        "\tfi\n"
        "\n"
        "configure: ansible-galaxy\n"
        "\t@if [ -f infra/ansible/playbooks/site.yml ]; then \\\n"
        "\t  cd infra/ansible && ansible-playbook playbooks/site.yml; \\\n"
        "\telse \\\n"
        "\t  echo 'No infra/ansible playbook (serverless / k8s-only workspace)'; \\\n"
        "\tfi\n"
        "\n"
        "deploy: cloud-up configure\n"
        "\t@$(MAKE) outputs\n"
        "\n"
        "cloud-down:\n"
        f"{destroy_recipe}"
        "\n"
        "outputs:\n"
        f"{output_recipe}"
    )
    path = workspace_dir / "Makefile"
    path.write_text(content, encoding="utf-8")
    return ["Makefile"]
