"""Advisory build + run + HTTP probe verification for workspace Dockerfiles.

This validates that a service's Dockerfile (either shipped by the repo or
generated by Launchpad when the repo lacks one) actually builds and serves
traffic, *before* a full provision. It is deliberately non-blocking: any
failure is reported as an advisory warning rather than raising, mirroring the
self-heal philosophy of ``preview_build`` (which regenerates and retries at
deploy time).

Reuses existing machinery rather than reimplementing it:
- ``preview_build._ensure_dockerfile`` / ``dockerfile_scaffold`` for generation
- ``preview_build._docker_build`` for the real image build
- ``attach_deploy._find_workspace_dockerfile`` + EXPOSE parsing for context
"""

from __future__ import annotations

import time
from dataclasses import asdict, dataclass
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from app.core.logging import get_logger, sanitize_log_message

logger = get_logger(__name__)

# Verify status values (kept as plain strings for a stable JSON contract).
STATUS_VERIFIED = "verified"
STATUS_WARNING = "warning"
STATUS_SKIPPED = "skipped"

_PROBE_ATTEMPTS = 15
_PROBE_INTERVAL_SECONDS = 2.0
_RUN_STARTUP_GRACE_SECONDS = 1.5
_DEFAULT_LISTEN_PORT = 8080


@dataclass(slots=True)
class DockerfileVerifyResult:
    """Advisory result of verifying a single service's Dockerfile."""

    service: str
    status: str = STATUS_SKIPPED
    used_repo_dockerfile: bool = False
    generated_stack: str | None = None
    built: bool = False
    ran: bool = False
    probe_ok: bool = False
    listen_port: int | None = None
    warning: str | None = None
    logs_tail: str | None = None

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


def _docker_available() -> bool:
    """Reuse the preview-build docker availability probe."""
    from app.services.preview_build import _docker_available as available

    return available()


def _expose_port(dockerfile_path: Path, *, fallback: int) -> int:
    """Prefer the Dockerfile EXPOSE port so the probe hits the app, not nginx :80."""
    from app.services.attach_deploy import _EXPOSE_RE

    try:
        text = dockerfile_path.read_text(encoding="utf-8")
    except OSError:
        return fallback
    match = _EXPOSE_RE.search(text)
    if match:
        try:
            port = int(match.group(1))
            if 1 <= port <= 65535:
                return port
        except ValueError:
            pass
    return fallback


def _probe_http(host_port: int) -> tuple[bool, str]:
    """Poll a locally published container port until it serves an HTTP response.

    Mirrors ``preview_smoke`` semantics: 2xx/3xx are healthy, and 401/403 count
    as reachable (the app is up but unauthenticated).
    """
    url = f"http://127.0.0.1:{host_port}/"
    last = "no_response"
    for _ in range(_PROBE_ATTEMPTS):
        req = Request(url, method="GET", headers={"User-Agent": "Launchpad-Dockerfile-Verify/1.0"})
        try:
            with urlopen(req, timeout=5.0) as response:  # noqa: S310 - loopback probe only
                code = int(getattr(response, "status", 200) or 200)
                if 200 <= code < 400:
                    return True, f"ok:{code}"
                last = f"unexpected_status:{code}"
        except HTTPError as exc:
            if exc.code in {401, 403}:
                return True, f"reachable_auth_required:{exc.code}"
            last = f"http_error:{exc.code}"
        except (URLError, TimeoutError, ConnectionError):
            last = "connection_refused"
        except Exception as exc:  # noqa: BLE001 - advisory probe, never fatal
            last = f"error:{sanitize_log_message(str(exc))[:120]}"
        time.sleep(_PROBE_INTERVAL_SECONDS)
    return False, last


def verify_service_dockerfile(
    context: Path,
    *,
    service_name: str = "app",
    dockerfile_rel: str = "Dockerfile",
    listen_port: int | None = None,
    force_regenerate: bool = False,
) -> DockerfileVerifyResult:
    """Build, run, and probe a single service's Dockerfile (advisory, never raises)."""
    result = DockerfileVerifyResult(service=service_name)

    if not context.is_dir():
        result.status = STATUS_WARNING
        result.warning = "context directory not found"
        return result

    if not _docker_available():
        result.status = STATUS_SKIPPED
        result.warning = "docker_unavailable"
        return result

    from app.services.preview_build import PreviewBuildError, _docker_build, _ensure_dockerfile

    target = context / dockerfile_rel
    result.used_repo_dockerfile = target.is_file() and not force_regenerate

    # Ensure a Dockerfile exists (generate from detected stack when missing).
    try:
        result.generated_stack = _ensure_dockerfile(
            context, dockerfile_rel=dockerfile_rel, force=force_regenerate
        )
    except PreviewBuildError as exc:
        result.status = STATUS_WARNING
        result.warning = f"no Dockerfile and stack undetectable: {sanitize_log_message(str(exc))[:200]}"
        return result

    resolved_port = int(listen_port) if listen_port else _expose_port(
        context / dockerfile_rel, fallback=_DEFAULT_LISTEN_PORT
    )
    result.listen_port = resolved_port

    tag = f"lp-verify-{_safe_tag(service_name)}:probe"
    try:
        _docker_build(context=context, dockerfile=dockerfile_rel, tag=tag)
    except PreviewBuildError as exc:
        result.status = STATUS_WARNING
        result.warning = f"docker build failed: {sanitize_log_message(str(exc))[:400]}"
        return result
    result.built = True

    ran, probe_ok, logs_tail, run_warning = _run_and_probe(tag=tag, container_port=resolved_port)
    result.ran = ran
    result.probe_ok = probe_ok
    result.logs_tail = logs_tail
    if probe_ok:
        result.status = STATUS_VERIFIED
    else:
        result.status = STATUS_WARNING
        result.warning = run_warning or "container did not serve a healthy response"

    _remove_image(tag)
    return result


def _run_and_probe(*, tag: str, container_port: int) -> tuple[bool, bool, str | None, str | None]:
    """Run the built image detached, publish its port, probe it, then tear down."""
    import docker

    client = docker.from_env()
    container = None
    try:
        container = client.containers.run(
            tag,
            detach=True,
            ports={f"{container_port}/tcp": None},
            labels={"launchpad-dockerfile-verify": "1"},
        )
        time.sleep(_RUN_STARTUP_GRACE_SECONDS)
        container.reload()
        if container.status == "exited":
            logs = _container_logs_tail(container)
            return False, False, logs, "container exited immediately after start"

        host_port = _published_host_port(container, container_port)
        if host_port is None:
            logs = _container_logs_tail(container)
            return True, False, logs, "container port was not published"

        probe_ok, detail = _probe_http(host_port)
        logs = _container_logs_tail(container)
        return True, probe_ok, logs, None if probe_ok else f"probe failed ({detail})"
    except Exception as exc:  # noqa: BLE001 - advisory run, never fatal
        return False, False, None, f"docker run failed: {sanitize_log_message(str(exc))[:300]}"
    finally:
        if container is not None:
            try:
                container.stop(timeout=3)
            except Exception:  # noqa: BLE001 - best-effort cleanup
                pass
            try:
                container.remove(force=True)
            except Exception:  # noqa: BLE001 - best-effort cleanup
                pass


def _published_host_port(container: object, container_port: int) -> int | None:
    try:
        ports = container.attrs["NetworkSettings"]["Ports"]  # type: ignore[index]
        binding = ports.get(f"{container_port}/tcp") or []
        if binding:
            return int(binding[0]["HostPort"])
    except (KeyError, IndexError, ValueError, TypeError):
        return None
    return None


def _container_logs_tail(container: object, *, lines: int = 40) -> str | None:
    try:
        raw = container.logs(tail=lines)  # type: ignore[attr-defined]
        text = raw.decode("utf-8", "replace") if isinstance(raw, bytes) else str(raw)
        return sanitize_log_message(text.strip())[:2000] or None
    except Exception:  # noqa: BLE001 - logs are best-effort
        return None


def _remove_image(tag: str) -> None:
    try:
        import docker

        docker.from_env().images.remove(tag, force=True)
    except Exception:  # noqa: BLE001 - best-effort cleanup
        pass


def _safe_tag(name: str) -> str:
    cleaned = "".join(ch if ch.isalnum() else "-" for ch in (name or "app").lower()).strip("-")
    return (cleaned or "app")[:40]


def verify_workspace_dockerfiles(
    workspace_root: Path,
    *,
    services: list[dict[str, object]] | None = None,
) -> list[DockerfileVerifyResult]:
    """Verify every service in a workspace (advisory).

    ``services`` entries accept ``name``, ``path`` (relative to the workspace
    root), ``dockerfile_path``, and ``listen_port``. When omitted, the primary
    workspace Dockerfile is resolved via ``attach_deploy._find_workspace_dockerfile``.
    """
    if services:
        results: list[DockerfileVerifyResult] = []
        for spec in services:
            rel = str(spec.get("path") or ".").strip() or "."
            context = (workspace_root / rel).resolve()
            dockerfile_rel = str(spec.get("dockerfile_path") or "Dockerfile").strip() or "Dockerfile"
            raw_port = spec.get("listen_port")
            port = int(raw_port) if isinstance(raw_port, (int, str)) and str(raw_port).isdigit() else None
            results.append(
                verify_service_dockerfile(
                    context,
                    service_name=str(spec.get("name") or context.name or "app"),
                    dockerfile_rel=dockerfile_rel,
                    listen_port=port,
                )
            )
        return results

    from app.services.attach_deploy import _find_workspace_dockerfile

    found = _find_workspace_dockerfile(workspace_root)
    if found is None:
        # Fall back to the root context so generation can attempt a scaffold.
        return [verify_service_dockerfile(workspace_root, service_name=workspace_root.name or "app")]
    dockerfile, context = found
    dockerfile_rel = dockerfile.name if dockerfile.parent == context else str(dockerfile.relative_to(context))
    return [
        verify_service_dockerfile(
            context,
            service_name=context.name or "app",
            dockerfile_rel=dockerfile_rel,
        )
    ]
