"""Launchpad-script IaC: a smart gcloud/aws/az CLI workspace instead of Terraform.

The script reads the wizard resource flags (GKE, Artifact Registry, VPC, secrets, ...)
and only provisions what the selected plugin and app need. Image registries are skipped
when the workload uses an external hub. VM configuration stays in cloud-init unless the
user opts into Ansible/Puppet/Chef.
"""

from __future__ import annotations

from pathlib import Path

from app.schemas.cloud import (
    AwsCloudConfig,
    AzureCloudConfig,
    CloudflareCloudConfig,
    GcpCloudConfig,
    KubernetesImageSource,
    KubernetesWorkloadOptions,
    ProvisioningWizardRequest,
    SecretBackend,
    WorkspaceRuntimeMode,
)

LAUNCHPROVISION_RELPATH = "infra/launchProvision.sh"
_LEGACY_LAUNCHPAD_RELPATH = "provision/launchpad.sh"


def write_launchpad_script(workspace_dir: Path, request: ProvisioningWizardRequest) -> list[str]:
    body = _script_for(request)
    infra = workspace_dir / "infra"
    infra.mkdir(parents=True, exist_ok=True)
    script_path = workspace_dir / LAUNCHPROVISION_RELPATH
    script_path.write_text(body, encoding="utf-8")
    try:
        script_path.chmod(0o755)
    except OSError:
        pass
    legacy = workspace_dir / _LEGACY_LAUNCHPAD_RELPATH
    if legacy.is_file():
        try:
            legacy.unlink()
        except OSError:
            pass
    return [LAUNCHPROVISION_RELPATH]


def _plugin_label(request: ProvisioningWizardRequest) -> str:
    plugin = request.cloud_plugin
    if plugin and plugin.provider:
        svc = plugin.service or plugin.provider
        return f"{plugin.provider} ({svc})"
    return request.cloud.provider.value


def _uses_external_image(options: KubernetesWorkloadOptions | None) -> bool:
    if options is None:
        return False
    return options.image_source == KubernetesImageSource.EXTERNAL


def _script_for(request: ProvisioningWizardRequest) -> str:
    cloud = request.cloud
    if isinstance(cloud, GcpCloudConfig):
        return _gcp_script(request, cloud)
    if isinstance(cloud, AwsCloudConfig):
        return _aws_script(request, cloud)
    if isinstance(cloud, AzureCloudConfig):
        return _azure_script(request, cloud)
    if isinstance(cloud, CloudflareCloudConfig):
        return _cloudflare_script(request, cloud)
    return (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        "echo \"Launchpad script has no handler for this cloud.\"\n"
        "exit 1\n"
    )


def _header(request: ProvisioningWizardRequest) -> str:
    plugin = _plugin_label(request)
    return (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        f"# Generated by Launchpad (LaunchProvision) for {plugin}\n"
        "# Usage: bash infra/launchProvision.sh [up|down|outputs|configure]\n"
        "ACTION=\"${1:-up}\"\n"
        "NAME=" + _sh_quote(request.name) + "\n"
        "echo \"==> LaunchProvision $ACTION ($NAME)\"\n"
        "if [ \"$ACTION\" = \"configure\" ]; then\n"
        "  echo '==> LaunchConfig: instance uses first-boot / startup metadata'\n"
        "  exit 0\n"
        "fi\n"
    )


def _sh_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _gcp_script(request: ProvisioningWizardRequest, cloud: GcpCloudConfig) -> str:
    r = cloud.resources
    external = _uses_external_image(request.kubernetes_options)
    need_ar = r.artifact_registry and not external
    lines = [
        _header(request),
        f"PROJECT={_sh_quote(r.project_id)}\n",
        f"REGION={_sh_quote(r.region)}\n",
        "export CLOUDSDK_CORE_PROJECT=\"$PROJECT\"\n",
        "command -v gcloud >/dev/null || { echo 'gcloud CLI required'; exit 1; }\n",
        "gcloud config set project \"$PROJECT\" >/dev/null\n",
        "if [ \"$ACTION\" = \"outputs\" ]; then\n",
        "  echo project=\"$PROJECT\" region=\"$REGION\" name=\"$NAME\"\n",
        "  exit 0\n",
        "fi\n",
        "if [ \"$ACTION\" = \"down\" ]; then\n",
    ]
    if r.gke:
        lines.append(
            "  gcloud container clusters delete \"$NAME\" --region \"$REGION\" --quiet || true\n"
        )
    if r.cloud_run:
        lines.append("  gcloud run services delete \"$NAME\" --region \"$REGION\" --quiet || true\n")
    if r.compute_instance or request.runtime_mode == WorkspaceRuntimeMode.RUNNING_INSTANCE:
        lines.append("  gcloud compute instances delete \"$NAME\" --zone \"${REGION}-a\" --quiet || true\n")
    if need_ar:
        lines.append(
            "  gcloud artifacts repositories delete \"$NAME\" --location \"$REGION\" --quiet || true\n"
        )
    lines.append("  exit 0\nfi\n")
    lines.append("gcloud services enable compute.googleapis.com --quiet || true\n")
    if r.vpc:
        lines.append(
            "gcloud compute networks describe \"$NAME-vpc\" >/dev/null 2>&1 || \\\n"
            "  gcloud compute networks create \"$NAME-vpc\" --subnet-mode=custom\n"
        )
    if r.subnets and r.vpc:
        cidr = "10.10.0.0/20" if r.network_topology.value == "simple" else "10.10.0.0/24"
        lines.append(
            f"gcloud compute networks subnets describe \"$NAME-subnet\" --region \"$REGION\" >/dev/null 2>&1 || \\\n"
            f"  gcloud compute networks subnets create \"$NAME-subnet\" --network=\"$NAME-vpc\" "
            f"--region=\"$REGION\" --range={cidr}\n"
        )
    if need_ar:
        lines.append("gcloud services enable artifactregistry.googleapis.com --quiet || true\n")
        lines.append(
            "gcloud artifacts repositories describe \"$NAME\" --location \"$REGION\" >/dev/null 2>&1 || \\\n"
            "  gcloud artifacts repositories create \"$NAME\" --repository-format=docker "
            "--location \"$REGION\" --description=\"Launchpad images for $NAME\"\n"
        )
    elif external:
        lines.append("echo '==> Using an external image hub; skipping Artifact Registry'\n")
    if r.gke:
        lines.append("gcloud services enable container.googleapis.com --quiet || true\n")
        net = "--network \"$NAME-vpc\" --subnetwork \"$NAME-subnet\" " if r.vpc and r.subnets else ""
        lines.append(
            "gcloud container clusters describe \"$NAME\" --region \"$REGION\" >/dev/null 2>&1 || \\\n"
            f"  gcloud container clusters create \"$NAME\" --region \"$REGION\" {net}"
            "--num-nodes 1 --machine-type " + r.machine_type + " --quiet\n"
        )
        lines.append(
            "gcloud container clusters get-credentials \"$NAME\" --region \"$REGION\"\n"
        )
    if r.cloud_run:
        lines.append("gcloud services enable run.googleapis.com --quiet || true\n")
        image = "gcr.io/cloudrun/hello"
        lines.append(
            "gcloud run deploy \"$NAME\" --region \"$REGION\" --image "
            f"{image} --allow-unauthenticated --quiet || true\n"
        )
    if r.compute_instance:
        lines.append(
            "gcloud compute instances describe \"$NAME\" --zone \"${REGION}-a\" >/dev/null 2>&1 || \\\n"
            "  gcloud compute instances create \"$NAME\" --zone \"${REGION}-a\" "
            f"--machine-type={r.machine_type} "
            + ("--network \"$NAME-vpc\" --subnet \"$NAME-subnet\" " if r.vpc and r.subnets else "")
            + "--image-family=ubuntu-2404-lts-amd64 --image-project=ubuntu-os-cloud "
            "--metadata=startup-script='# Launchpad: install Docker and run the app container'\n"
        )
    if r.secret_backend == SecretBackend.SECRET_MANAGER:
        lines.append("gcloud services enable secretmanager.googleapis.com --quiet || true\n")
        lines.append("echo '==> Secrets: Secret Manager (native Kubernetes Secrets skipped)'\n")
    else:
        lines.append("echo '==> Secrets: native Kubernetes Secrets / manifests'\n")
    if r.cloud_sql:
        lines.append("gcloud services enable sqladmin.googleapis.com --quiet || true\n")
        lines.append(
            "gcloud sql instances describe \"$NAME-sql\" >/dev/null 2>&1 || \\\n"
            f"  gcloud sql instances create \"$NAME-sql\" --database-version="
            f"{r.cloud_sql_engine.value.upper()}_15 --tier=db-f1-micro --region=\"$REGION\"\n"
        )
    if r.cloud_storage:
        lines.append("gcloud storage buckets describe \"gs://$NAME-$PROJECT\" >/dev/null 2>&1 || \\\n")
        lines.append(
            "  gcloud storage buckets create \"gs://$NAME-$PROJECT\" --location \"$REGION\"\n"
        )
    if r.pubsub:
        lines.append("gcloud services enable pubsub.googleapis.com --quiet || true\n")
        lines.append("gcloud pubsub topics describe \"$NAME\" >/dev/null 2>&1 || gcloud pubsub topics create \"$NAME\"\n")
    if r.memorystore:
        lines.append("gcloud services enable redis.googleapis.com --quiet || true\n")
        lines.append(
            "gcloud redis instances describe \"$NAME\" --region \"$REGION\" >/dev/null 2>&1 || \\\n"
            "  gcloud redis instances create \"$NAME\" --size=1 --region \"$REGION\" --redis-version=redis_7_0\n"
        )
    if request.runtime_mode == WorkspaceRuntimeMode.KUBERNETES and r.gke:
        lines.append("echo '==> Apply Kubernetes manifests from infra/k8s when they exist'\n")
        lines.append("if [ -d infra/k8s ]; then kubectl apply -f infra/k8s || true; fi\n")
    if not request.ansible.enabled and (
        r.compute_instance or request.runtime_mode == WorkspaceRuntimeMode.RUNNING_INSTANCE
    ):
        lines.append("echo '==> VM config: Launchpad startup script (enable Ansible or a config plugin to replace)'\n")
    lines.append("echo '==> up complete'\n")
    return "".join(lines)


def _aws_script(request: ProvisioningWizardRequest, cloud: AwsCloudConfig) -> str:
    r = cloud.resources
    external = _uses_external_image(request.kubernetes_options)
    need_ecr = r.ecr and not external
    lines = [
        _header(request),
        f"REGION={_sh_quote(r.region)}\n",
        "export AWS_DEFAULT_REGION=\"$REGION\"\n",
        "command -v aws >/dev/null || { echo 'aws CLI required'; exit 1; }\n",
        "if [ \"$ACTION\" = \"outputs\" ]; then echo region=\"$REGION\" name=\"$NAME\"; exit 0; fi\n",
        "if [ \"$ACTION\" = \"down\" ]; then\n",
    ]
    if r.eks:
        lines.append("  aws eks delete-cluster --name \"$NAME\" || true\n")
    if need_ecr:
        lines.append("  aws ecr delete-repository --repository-name \"$NAME\" --force || true\n")
    lines.append("  exit 0\nfi\n")
    if r.vpc:
        lines.append("echo '==> Ensure a VPC (reuses default VPC if present)'\n")
        lines.append(
            "VPC_ID=$(aws ec2 describe-vpcs --filters Name=isDefault,Values=true "
            "--query 'Vpcs[0].VpcId' --output text)\n"
        )
    if need_ecr:
        lines.append(
            "aws ecr describe-repositories --repository-names \"$NAME\" >/dev/null 2>&1 || \\\n"
            "  aws ecr create-repository --repository-name \"$NAME\" >/dev/null\n"
        )
    elif external:
        lines.append("echo '==> Using an external image hub; skipping ECR'\n")
    if r.eks:
        lines.append(
            "aws eks describe-cluster --name \"$NAME\" >/dev/null 2>&1 || \\\n"
            "  echo 'Create the EKS cluster with eksctl or enable Terraform if you need a full control plane from CLI.'\n"
        )
    if r.ec2:
        lines.append("echo '==> EC2: Launchpad user-data installs Docker unless a config plugin is selected'\n")
    if r.secrets_manager:
        lines.append("echo '==> Secrets: AWS Secrets Manager'\n")
    if r.rds:
        lines.append("echo '==> RDS requested (" + r.rds_engine.value + ") - create after VPC/subnets exist'\n")
    lines.append("echo '==> up complete'\n")
    return "".join(lines)


def _azure_script(request: ProvisioningWizardRequest, cloud: AzureCloudConfig) -> str:
    r = cloud.resources
    external = _uses_external_image(request.kubernetes_options)
    need_acr = r.acr and not external
    lines = [
        _header(request),
        f"LOCATION={_sh_quote(r.location)}\n",
        f"RG={_sh_quote(r.resource_group)}\n",
        "command -v az >/dev/null || { echo 'az CLI required'; exit 1; }\n",
        "if [ \"$ACTION\" = \"outputs\" ]; then echo rg=\"$RG\" location=\"$LOCATION\"; exit 0; fi\n",
        "az group create --name \"$RG\" --location \"$LOCATION\" >/dev/null\n",
        "if [ \"$ACTION\" = \"down\" ]; then az group delete --name \"$RG\" --yes --no-wait; exit 0; fi\n",
    ]
    if r.vnet:
        lines.append(
            "az network vnet show --resource-group \"$RG\" --name \"$NAME-vnet\" >/dev/null 2>&1 || \\\n"
            "  az network vnet create --resource-group \"$RG\" --name \"$NAME-vnet\" "
            "--address-prefix 10.20.0.0/16 --subnet-name \"$NAME-subnet\" --subnet-prefix 10.20.0.0/20 >/dev/null\n"
        )
    if need_acr:
        lines.append(
            "az acr show --name \"${NAME//-/}\" --resource-group \"$RG\" >/dev/null 2>&1 || \\\n"
            "  az acr create --resource-group \"$RG\" --name \"${NAME//-/}\" --sku Basic >/dev/null\n"
        )
    elif external:
        lines.append("echo '==> Using an external image hub; skipping ACR'\n")
    if r.aks:
        lines.append(
            "az aks show --resource-group \"$RG\" --name \"$NAME\" >/dev/null 2>&1 || \\\n"
            "  az aks create --resource-group \"$RG\" --name \"$NAME\" --node-count 1 "
            "--generate-ssh-keys --yes\n"
        )
        lines.append("az aks get-credentials --resource-group \"$RG\" --name \"$NAME\" --overwrite-existing\n")
    if r.container_apps:
        lines.append("echo '==> Azure Container Apps requested'\n")
    if r.key_vault:
        lines.append("echo '==> Secrets: Azure Key Vault'\n")
    else:
        lines.append("echo '==> Secrets: native Kubernetes Secrets / manifests'\n")
    lines.append("echo '==> up complete'\n")
    return "".join(lines)


def _cloudflare_script(request: ProvisioningWizardRequest, cloud: CloudflareCloudConfig) -> str:
    r = cloud.resources
    lines = [
        _header(request),
        "command -v npx >/dev/null || { echo 'npx (Node.js) required for Workers/Pages'; exit 1; }\n",
        "if [ \"$ACTION\" = \"down\" ]; then echo 'Delete the Worker/Pages project in the Cloudflare dashboard or wrangler.'; exit 0; fi\n",
        "if [ \"$ACTION\" = \"outputs\" ]; then echo name=\"$NAME\"; exit 0; fi\n",
    ]
    if r.workers:
        lines.append("echo '==> Cloudflare Workers (wrangler deploy when wrangler.toml is present)'\n")
        lines.append("if [ -f wrangler.toml ]; then npx wrangler deploy; fi\n")
    if r.pages:
        lines.append("echo '==> Cloudflare Pages project $NAME'\n")
    if r.tunnels:
        lines.append("echo '==> Cloudflare Tunnel requested'\n")
    lines.append("echo '==> up complete'\n")
    return "".join(lines)
