"""Add infrastructure_config_json to provisioning_workspaces

Revision ID: 3e76b5c8ce7c
Revises: 0038_plugin_owner_visibility
Create Date: 2026-08-24 10:26:27.676995
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3e76b5c8ce7c'
down_revision: str | None = '0038_plugin_owner_visibility'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_nodes', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PENDING', 'ONLINE', 'OFFLINE', 'REVOKED', name='agent_node_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.create_foreign_key(None, 'environments', 'environments', ['promoted_from_id'], ['id'], ondelete='SET NULL')
    op.drop_column('environments', 'public_preview_url')
    op.alter_column('organizations', 'plan',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('free', 'pro', name='org_plan', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('project_invites', 'role',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('owner', 'admin', 'member', 'viewer', name='project_invite_role', native_enum=False),
               existing_nullable=False)
    op.alter_column('project_memberships', 'role',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('owner', 'admin', 'member', 'viewer', name='project_role', native_enum=False),
               existing_nullable=False)
    op.add_column('provisioning_workspaces', sa.Column('infrastructure_config_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provisioning_workspaces', 'infrastructure_config_json')
    op.alter_column('project_memberships', 'role',
               existing_type=sa.Enum('owner', 'admin', 'member', 'viewer', name='project_role', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('project_invites', 'role',
               existing_type=sa.Enum('owner', 'admin', 'member', 'viewer', name='project_invite_role', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('organizations', 'plan',
               existing_type=sa.Enum('free', 'pro', name='org_plan', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.add_column('environments', sa.Column('public_preview_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'environments', type_='foreignkey')
    op.alter_column('agent_nodes', 'status',
               existing_type=sa.Enum('PENDING', 'ONLINE', 'OFFLINE', 'REVOKED', name='agent_node_status', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    # ### end Alembic commands ###
