"""Add public_preview_url to environments

Revision ID: 5b6785654c2c
Revises: 0018_ephemeral_datastores
Create Date: 2026-08-03 11:50:44.735517
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5b6785654c2c'
down_revision: str | None = '0018_ephemeral_datastores'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Enum('PROVISION_INITIATED', 'PROVISION_SUCCEEDED', 'PROVISION_FAILED', 'REBUILD_INITIATED', 'REBUILD_SUCCEEDED', 'REBUILD_FAILED', 'PAUSE_SUCCEEDED', 'RESUME_SUCCEEDED', 'TEARDOWN_INITIATED', 'TEARDOWN_SUCCEEDED', 'TEARDOWN_FAILED', 'DRIFT_DETECTED', 'EXECUTION_FAILED', name='audit_action', native_enum=False),
               existing_nullable=False)
    op.alter_column('audit_logs', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PENDING', 'SUCCESS', 'FAILURE', 'REJECTED', name='audit_status', native_enum=False),
               existing_nullable=False)
    op.alter_column('deployment_logs', 'log_level',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('INFO', 'WARN', 'ERROR', name='log_level', native_enum=False),
               existing_nullable=False)
    op.alter_column('deployment_logs', 'stage',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('INIT', 'VALIDATE', 'PLAN', 'BUILD', 'APPLY', name='execution_stage', native_enum=False),
               existing_nullable=True)
    op.add_column('environments', sa.Column('public_preview_url', sa.String(length=512), nullable=True))
    op.alter_column('environments', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PROVISIONING', 'RUNNING', 'PAUSED', 'TEARDOWN_PENDING', 'DESTROYED', 'FAILED', name='environment_status', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_environments_git_branch'), table_name='environments')
    op.alter_column('org_invites', 'role',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('owner', 'admin', 'member', 'viewer', name='org_invite_role', native_enum=False),
               existing_nullable=False)
    op.alter_column('org_memberships', 'role',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('owner', 'admin', 'member', 'viewer', name='org_role', native_enum=False),
               existing_nullable=False)
    op.alter_column('org_sso_role_mappings', 'role',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('owner', 'admin', 'member', 'viewer', name='org_sso_role', native_enum=False),
               existing_nullable=False)
    op.create_unique_constraint(None, 'organizations', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.alter_column('org_sso_role_mappings', 'role',
               existing_type=sa.Enum('owner', 'admin', 'member', 'viewer', name='org_sso_role', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('org_memberships', 'role',
               existing_type=sa.Enum('owner', 'admin', 'member', 'viewer', name='org_role', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('org_invites', 'role',
               existing_type=sa.Enum('owner', 'admin', 'member', 'viewer', name='org_invite_role', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.create_index(op.f('ix_environments_git_branch'), 'environments', ['git_branch'], unique=False)
    op.alter_column('environments', 'status',
               existing_type=sa.Enum('PROVISIONING', 'RUNNING', 'PAUSED', 'TEARDOWN_PENDING', 'DESTROYED', 'FAILED', name='environment_status', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('environments', 'public_preview_url')
    op.alter_column('deployment_logs', 'stage',
               existing_type=sa.Enum('INIT', 'VALIDATE', 'PLAN', 'BUILD', 'APPLY', name='execution_stage', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('deployment_logs', 'log_level',
               existing_type=sa.Enum('INFO', 'WARN', 'ERROR', name='log_level', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('audit_logs', 'status',
               existing_type=sa.Enum('PENDING', 'SUCCESS', 'FAILURE', 'REJECTED', name='audit_status', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.Enum('PROVISION_INITIATED', 'PROVISION_SUCCEEDED', 'PROVISION_FAILED', 'REBUILD_INITIATED', 'REBUILD_SUCCEEDED', 'REBUILD_FAILED', 'PAUSE_SUCCEEDED', 'RESUME_SUCCEEDED', 'TEARDOWN_INITIATED', 'TEARDOWN_SUCCEEDED', 'TEARDOWN_FAILED', 'DRIFT_DETECTED', 'EXECUTION_FAILED', name='audit_action', native_enum=False),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
