"""add_ttl_duration_seconds

Revision ID: 8f2609e25c30
Revises: 0034_lifecycle_promotions
Create Date: 2026-08-17 13:31:05.862393
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8f2609e25c30'
down_revision: str | None = '0034_lifecycle_promotions'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('ttl_duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environments', 'ttl_duration_seconds')
    # ### end Alembic commands ###
